import type { MissionMeta, Badge } from '../types';

export const MISSIONS: MissionMeta[] = [
  {
    id: 'm1_footprint',
    number: '01',
    title: 'THE INVISIBLE INTERNET',
    tagline: 'Trace the scattered digital footprint of a public target.',
    concept: 'Digital Footprints, Metadata & Information Aggregation',
    estimatedDuration: '10 MIN',
    difficulty: 'RECRUIT',
    badgeTitle: 'PRIVACY GUARDIAN',
    badgeDesc: 'Identified critical metadata leaks and locked down a vulnerable public profile.',
    icon: 'Footprints',
    xpReward: 300,
    narrativeBriefing: 'Alex reported an alarming privacy breach. Scattered public posts, geo-tags, timestamps, and comments seem harmless on their own, but when pieced together, they reveal an exact daily schedule and personal routine. Investigate the profile, connect the clues, and activate Privacy Defender to scrub the exposure.',
  },
  {
    id: 'm2_browser',
    number: '02',
    title: 'EAVESDROP ON YOUR BROWSER',
    tagline: 'Inspect the hidden network traffic behind web interfaces.',
    concept: 'Client-Server HTTP, APIs, JSON & Information Disclosure',
    estimatedDuration: '15 MIN',
    difficulty: 'OPERATIVE',
    badgeTitle: 'NETWORK DETECTIVE',
    badgeDesc: 'Intercepted hidden API payloads and fixed excessive server data exposure.',
    icon: 'Radio',
    xpReward: 350,
    narrativeBriefing: 'Whenever you click a button on the web, a silent conversation happens between your browser and the server. In this mission, you will open the HUD Network Inspector, analyze HTTP requests and JSON payloads, discover a dangerous internal secret leaking in an API response, and apply a backend fix.',
  },
  {
    id: 'm3_access',
    number: '03',
    title: 'BREAK IT. FIX IT.',
    tagline: 'Test authentication vs authorization in a flawed school portal.',
    concept: 'Authentication vs Authorization & Broken Access Control (IDOR)',
    estimatedDuration: '15 MIN',
    difficulty: 'OPERATIVE',
    badgeTitle: 'SECURITY RESEARCHER',
    badgeDesc: 'Proved broken access control vulnerability and implemented server-side authorization enforcement.',
    icon: 'ShieldAlert',
    xpReward: 400,
    narrativeBriefing: 'A school portal allows students to log in. However, the developers forgot a golden security rule: Being logged in does NOT mean you should see everyone else’s data! Exploit the flawed access control in a safe simulator, understand the difference between AuthN and AuthZ, then activate the server-side security rule.',
  },
  {
    id: 'm4_cipher',
    number: '04',
    title: 'CRACK THE SECRET',
    tagline: 'Decrypt intercepted transmissions and uncover cipher weaknesses.',
    concept: 'Encryption, Decryption, Caesar Ciphers & Cryptographic Keyspace',
    estimatedDuration: '10 MIN',
    difficulty: 'OPERATIVE',
    badgeTitle: 'CODEBREAKER',
    badgeDesc: 'Decoded intercepted cryptographic ciphers and tested keyspace vulnerabilities.',
    icon: 'KeyRound',
    xpReward: 350,
    narrativeBriefing: 'Our antennas intercepted an encrypted transmission containing the ciphertext "KHOOR". Use our cryptographic decipher console, adjust the letter shift key, observe the dual alphabet transform wheel, test custom messages, and execute a brute-force sweep to understand why small keyspaces fail in real-world security.',
  },
  {
    id: 'm5_phishing',
    number: '05',
    title: 'OUTSMART THE HUMAN HACKER',
    tagline: 'Analyze social engineering tactics, deceptive URLs, and urgency traps.',
    concept: 'Phishing, Social Engineering, Spoofed Domains & Verification',
    estimatedDuration: '10 MIN',
    difficulty: 'VETERAN',
    badgeTitle: 'SCAM HUNTER',
    badgeDesc: 'Outmaneuvered sophisticated phishing, domain spoofing, and OTP theft attempts.',
    icon: 'FishHook',
    xpReward: 400,
    narrativeBriefing: 'Attackers don’t just hack code—they hack human psychology! Your cyber phone inbox is receiving incoming messages. Some are authentic; others use urgent bans, fake prizes, and spoofed domains to steal credentials and 2FA tokens. Inspect senders, check headers, verify out-of-band, and make evidence-based calls.',
  }
];

export const BADGES: Badge[] = [
  {
    id: 'badge_m1',
    missionId: 'm1_footprint',
    title: 'PRIVACY GUARDIAN',
    description: 'Mastered digital footprint analysis and metadata hardening.',
    iconName: 'ShieldCheck',
  },
  {
    id: 'badge_m2',
    missionId: 'm2_browser',
    title: 'NETWORK DETECTIVE',
    description: 'Intercepted live API traffic and eliminated data disclosure vulnerabilities.',
    iconName: 'Binary',
  },
  {
    id: 'badge_m3',
    missionId: 'm3_access',
    title: 'SECURITY RESEARCHER',
    description: 'Exposed Broken Access Control and enforced strict server-side authorization.',
    iconName: 'LockKeyhole',
  },
  {
    id: 'badge_m4',
    missionId: 'm4_cipher',
    title: 'CODEBREAKER',
    description: 'Decrypted intercepted communications and analyzed cryptographic keyspaces.',
    iconName: 'Cpu',
  },
  {
    id: 'badge_m5',
    missionId: 'm5_phishing',
    title: 'SCAM HUNTER',
    description: 'Defended against social engineering, deceptive links, and credential theft.',
    iconName: 'Crosshair',
  },
  {
    id: 'badge_blackout',
    missionId: 'blackout',
    title: 'CYBERQUEST MASTER OPERATIVE',
    description: 'Solved the full multi-vector school security incident in Operation Blackout.',
    iconName: 'Award',
  },
  {
    id: 'badge_protocol_zero',
    missionId: 'protocol_zero',
    title: 'PROTOCOL ZERO SPECIALIST',
    description: 'Neutralized the classified instructor bonus threat vector.',
    iconName: 'Zap',
  }
];
